import './globals.css';

import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';

import { Header } from './components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={GeistSans.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
